"""tablas iniciales: employees, shift_rules, shifts, shift_rules_employees

Revision ID: bb99f561dea3
Revises: 
Create Date: 2026-09-08 13:43:27.416716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb99f561dea3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('shift_rules',
    sa.Column('shift_rule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_hours_day', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_hours_week', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('max_hours_day > 0', name='ck_shift_rules_max_hours_day_positive'),
    sa.CheckConstraint('max_hours_week > 0', name='ck_shift_rules_max_hours_week_positive'),
    sa.PrimaryKeyConstraint('shift_rule_id')
    )
    op.create_table('shift_rules_employees',
    sa.Column('shift_rule_r_employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_rule_id'], ['shift_rules.shift_rule_id'], ),
    sa.PrimaryKeyConstraint('shift_rule_r_employee_id'),
    sa.UniqueConstraint('employee_id', name='uq_shift_rules_employees_employee_id')
    )
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index('ix_shifts_employee_date', 'shifts', ['employee_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shifts_employee_date', table_name='shifts')
    op.drop_table('shifts')
    op.drop_table('shift_rules_employees')
    op.drop_table('shift_rules')
    op.drop_table('employees')
    # ### end Alembic commands ###
